name: social_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  shared_preferences: ^2.0.6
  hexcolor: ^2.0.4
  webview_flutter: ^2.0.8
  dio: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.0.7
  carousel_slider: ^4.0.0
  flutter_conditional_rendering: ^2.0.0
  firebase_core: ^1.5.0
  firebase_storage: ^10.0.2
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.3.0
  google_nav_bar: ^5.0.5
  image_picker: ^0.8.3+2
  firebase: ^9.0.1
  firebase_messaging: ^10.0.7
  like_button: ^2.0.4
  splash_screen_view: ^3.0.0
  liquid_pull_to_refresh: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/s.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
